### ISSUE TITLE
Qwebview not found

### ISSUE THREAD

**Issue by fred-g** [KaOS-Community-Packages/nextcloud-client#2]
Hi,

Try to build via `kcp -i`.
qtwebkit-tp is installed but it doesn't find qwebview.

Is something else missing ?

`[ 86%] Building CXX object src/gui/CMakeFiles/nextcloud.dir/creds/shibbolethcredentials.cpp.o
In file included from /tmp/nextcloud-client/src/nextcloud-client/client/src/gui/creds/shibbolethcredentials.cpp:22:0:
/tmp/nextcloud-client/src/nextcloud-client/client/src/gui/creds/shibboleth/shibbolethwebview.h:20:20: erreur fatale : QWebView : Aucun fichier ou dossier de ce type
compilation terminée.
make[2]: *** [src/gui/CMakeFiles/nextcloud.dir/build.make:1695: src/gui/CMakeFiles/nextcloud.dir/creds/shibbolethcredentials.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:340: src/gui/CMakeFiles/nextcloud.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
==> ERREUR : Une erreur s’est produite dans build().
    Abandon...
exit status 2
`

++

**Comment by Adurol** [comment]
This is an issue with qtwebkit-tp, and should be solved with qtwebkit-tp-5.6.2.3-**3** (which is as of writing this still in the build repo).

**Comment by fred-g** [comment]
ok, thank you.

regards.

**Comment by demmm** [comment]
Latest qtwebkit-tp with the needed fix for the above build issue has moved to all users, retry the build after updating, should be possible to close this issue now.

**Comment by fred-g** [comment]
Yes, all is OK.

Thank you :)
